ocr_web/models.py
from ocr_web import db

class UserInformation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    template_name= db.Column(db.String(200), nullable=False)

ocr_web/__init__.py
from flask import Flask

#ORM 사용을 위한 import
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

#Flaks-Migrate-파이썬 모델을 이용해 테이블생성, 컬럼추가등의 작업을 하게 해줌
db = SQLAlchemy()
migrate = Migrate()


#application factory
def create_app():
	app = Flask(__name__)

	#config.py에 작성한 항목을 app.config 환경변수로 부르기 위함
	app.config.from_object(config)

	
	#for ORM - 위에서 만든 전역변수(db,migrate)를 초기화
	db.init_app(app)
	migrate.init_app(app,db)

	from . import models

	#for blue print
	from .views import main_views
	app.register_blueprint(main_views.bp)
	
	return app

if __name__=='__main__':
	create_app().run(host='0.0.0.0',port=8000,debug=True)

ocr_web/views/main_views.py
from flask import Blueprint, render_template,request
import json
import os


from ocr_web.models import UserInformation

bp = Blueprint('main',__name__,url_prefix='/')

@bp.route('/',methods=('GET','POST'))
def main_page():
	if request.method =="GET":
		select_list=['전체','문단별']
		return render_template('web_page/first_page.html',select_list=select_list)
	elif request.method =="POST":
		test2=request.form.get('btn_select')
		
		if test2 =="일반":
			select_list=['전체','문단별']
			return render_template('web_page/first_page.html',select_list=select_list,test2=test2)
		elif test2=="지정":
			return render_template('web_page/first_page.html',test2=test2)

@bp.route('/2',methods=('GET','POST'))
def hello_ocr2():
	test_request={"adsf":89706}
	test_request2=json.dumps(test_request)
	if request.method=="GET":
		return render_template('web_page/first_page_result.html',test_request=test_request2)

@bp.route('/3')
def hello_ocr3():
	return render_template('web_page/third_page.html')

ocr_web/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css')}}">
    <title>OCR</title>


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{{ url_for('main.main_page') }}">OCR</a>
        
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- 기본 템플릿 안에 삽입될 내용 -->
    {% block content %}
    {% endblock %}
</body>
</html>

ocr_web/templates/web_page/first_page.html
{% extends 'base.html'%}
{% block content %}
<style>
    #dropzone
    {
        border:2px dotted #3292A2;
        width:40%;
        height:800px;
        color:#92AAB0;
        text-align:center;
        font-size:24px;
        padding-top:12px;
        margin-top:10px;
        margin-left:100px;
    }
    #stateButton
    {
        width:40%;
        height:100px;
        color:#000000;
        text-align:center;
        margin-top:-800px;
        font-size:20px;
        float:right;
    }
   
</style>
<scirpt src="static/drag_drop.js"></scirpt>
<div id="dropzone">마우스로 파일을 드래그 하거나 여기를 클릭해서 업로드 해주세요</div> 


<div id= "stateButton">
    <form action='/' method="POST">
        <input type="submit" name="btn_select" value="일반">
        <input type="submit" name="btn_select" value="지정">
    </form>
    <form>
        <select name="selection_list">
            {% if select_list %}
                {% for item in select_list%}
                    <option value="item">{{item}}</option>
                {% endfor %}
            {% else %}
                <option value="none">template</option>
            {% endif %}
        </select>
    </form>
    {% if test2=="일반" %}
        <label><input type="checkbox" name="ocr_type" value="extraction_text">텍스트</label>
        <label><input type="checkbox" name="ocr_type" value="extraction_table">표</label>
        <label><input type="checkbox" name="ocr_type" value="extraction_picture">그림</label><br>
        <form action ="/2" method="GET">
            <input type="submit" name="result_change" value="텍스트 변환">
        </form>
    {% elif test2=="지정"%}
        <div id=table_scroll style="width:70%; height: 600px; overflow:auto; border-width:5px; border-color:#000000; border-style:solid">
            <table width="100% "border="1" cellspacing="0" cellpadding="0">
                <tr>
                    <th>No.</th>
                    <th>Value</th>
                </tr>
                <!--tr은 제목이 아닌 일반 표를 말하며 이부분은 인식한 값에 따라서 동적으로 생성되도록 해야한다-->
                <tr>
                    <td>adf</td>
                    <td>adf1</td>
                </tr>
            </table>
        </div>
        <div id=type_select_btn style="width:200px; height:100px">
            <input style="width:45%; height:50%; margin:3.5px" type="button" id="area_designation" value="AREA+"><br>
            <input type="button" id="save" value="SAVE" style="width:45%; height:50%; margin:3.5px">
            <form action ="/2" method="GET">
                <input type="submit" name="result_change" value="텍스트 변환" style="width:60%; height:50%;margin:3.5px">
            </form>
        </div> 
    {% endif %}
</div>



{% endblock %}

ocr_web/templates/web_page/first_page_result.html
{% extends 'base.html'%}
{% block content %}
<style>
    #selectBox
    {
        border:1px;
        padding:5px;
    }
    .container
    {
        width:100%;
        height:700px;
        background-color: #ffffff;
        margin:auto;
        margin-top:30px;
        box-sizing:content-box;
        padding-top: 5px;
        border-width:5px;
        border-color:coral;
        border-style: inset;
    }
    #select_button
    {
        width:100px;
        height:200px;
        background-color: #ffffff;
    }
    #ocr_content
    {
        width:90%;
        height:600px;
        margin: auto;
        margin-top: 10px;
        text-align: center;
        background-color:forestgreen;
    }
    .result_box
    {
        width: 100%;
        height:600px;
        background-color:#ffffff;
        border-width: 5px;
        border-color:coral;
        border-style:inset;
        margin:5px;
    }
    #select_file_type
    {
        width:100px;
        height:30px;
        float:right;
        margin-right: 50px;
    }
    
</style>
<div class=container>
    <span id = select_button>
      
        <input id="select_text1 "type="button" value="TEXT" onclick="alert('TEXT')">
        <input id="select_text2 "type="button" value="TABLE" onclick="alert('TABLE')">
    </span>
    <div id=ocr_content>
        <!--'result_ocr 삭제할수 있도록 우측에 쓰레기통 모양 버튼추가 필요'-->
        <span id="original_ocr" class="result_box">asdfadfad</span>
        <span id="result_ocr" class="result_box">asdfsad</span>
    </div>
</div>
<span id=select_file_type>
    <select name="file_type" id="file_select">
        <option value="default">==선택==</option>
        <option value="txt"><b>.txt</b></option>
        <option value="csv"><b>.csv</b></option>
    </select>
    <div>
        <input type="button" id="download_ok" value="Download" onclick=
        "alert('select  '+document.getElementById('file_select').options[document.getElementById('file_select').options.selectedIndex].value)">
    </div>
</span>
<script type="text/javascript">
    var data='{{test_request}}'
    var data2={"asdfasd":05}
    document.write(data)
</script>
{% endblock %}